### ISSUE TITLE
Getting this error XMLHttpRequest cannot load https://dc.services.visualstudio.com/v2/track. Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by calloncampbell** [khaines/angular-applicationinsights#32]
Hi,

I've added this to my AngularJS app and with option "autoPageViewTracking" set to true, I get the following error:

XMLHttpRequest cannot load https://dc.services.visualstudio.com/v2/track. Request header field Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by khaines** [comment]
Which version are you running? 0.2.6 has a fix for overriding configured default headers during the telemetry request, so that headers the target system doesn't accept (like Authorization) are removed. This should have addressed the cause for this error.

**Comment by khaines** [comment]
https://github.com/khaines/angular-applicationinsights/blob/master/dist/angular-applicationinsights.js#L870 Lines 870 through 877 should be filtering out any undesired default headers for the request

**Comment by calloncampbell** [comment]
I'm using 0.2.6.

**Comment by khaines** [comment]
Now I'm curious about how your application is setup. Are you using a custom service for $http or overriding the default for any requests?
  
 Also if you have a reproducible example, I would be happy to debug it to try and understand why what I'm doing in the code (clearing out any headers) before sending the $http request is not having the intended result.
  
 My email address is on my public profile if you would rather discuss these details privately. I can update this thread with any results afterwards.
  
 Cheers,
  
 Ken
  
  
  

----------------------------------------

**Comment by khaines** [comment]
Thank you again @calloncampbell for the example of the issue.

Confirmed in the investigation that the injector is adding header values that the appinsights module cannot overwrite, so a correction branch (https://github.com/khaines/angular-applicationinsights/tree/feature/xhr-wrapper) was created changing how the module creates http requests, using the bare XHR object  vs $http, but still allows for mocking @ test time.  I haven't finished correcting all the tests yet in that branch but the modified module did work on a smoke tests.

**Comment by khaines** [comment]
This issue is resolved in version v0.2.7

**Comment by bobwiller** [comment]
FYI, I am still seeing this issue in 0.2.7 - I am using Auth0 to authenticate users.  Not sure what other information I can provide to help debug?

**Comment by khaines** [comment]
Is this on a page/app I can access? I can debug it that way if it will be
helpful. You can send me details directly to the email in my public profile
as well, if you don't want them shared.

Cheers,

Ken

**Comment by jrmcdona** [comment]
Does this only happen when running with localhost?  I get the error too and I have the latest angular-applicationinsights source.
